CREATE TABLE cars
(
    PLATE    VARCHAR(10) PRIMARY KEY,
    TYPE   VARCHAR(15) NULL,
    INSIDE_PARKING_LOT BOOLEAN NOT NULL DEFAULT FALSE,
    STAYING_MINUTES INT NULL,
    START_TIMESTAMP TIMESTAMP NULL,
    END_TIMESTAMP TIMESTAMP NULL
);