server:
  port: 8782
  servlet:
    contextPath: /parking
logging:
  level:
    org.springframework.web: ERROR
    com.eglobal.ebind.atm: DEBUG
spring:
  codec:
    max-in-memory-size: 1000MB
  application:
    name: mx-ms-parking-main
    jackson:
      time-zone: America/Mexico_City
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username:
    password:
    driver: org.postgresql.Driver
    poolName: ${spring.application.name}-poolg
    maximumPoolSize: 20
    minimumIdle: 2
    properties:
      cachePrepStmts: true
      prepStmtCacheSize: 256
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    properties:
      hibernate:
        default_schema:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true

